# Generated by Django 2.2.5 on 2020-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FileField(upload_to='documentos')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('adicionado', models.DateField(auto_now_add=True, verbose_name='Adicionado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='periodo_fin',
            field=models.IntegerField(default=2020, verbose_name='Fin de Periodo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='periodo_inicio',
            field=models.IntegerField(default=2020, verbose_name='Inicio de Periodo'),
        ),
    ]
