# Generated by Django 2.2.5 on 2020-02-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20200212_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='documento',
        ),
    ]
