# Generated by Django 2.2.5 on 2020-02-13 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_remove_documento_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documentos'),
            preserve_default=False,
        ),
    ]
