# Generated by Django 2.2.5 on 2020-02-14 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_documento_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Publicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='resumen',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resumen'),
        ),
    ]
