# Generated by Django 2.2.5 on 2020-02-14 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20200213_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.Autor'),
            preserve_default=False,
        ),
    ]
